### ISSUE TITLE
hi 

### ISSUE THREAD

**Issue by asadalibest1** [eneax/gatsby-restaurant#6]
hi, eneax! I am asad ali, hope you are good and going well in your career. i want to ask a question regarding this website that I clone it into my local system but how i can start it? Can you Plz help me?

**Comment by eneax** [comment]
Hi @asadalibest1,

to run this project, you must first create a [Contentful](https://www.contentful.com) account.
Then, create a `.env.development` file in your root directory with the following variables:

```
SPACE_ID=
ACCESS_TOKEN=
```

Finally, set the variables with the values provided by Contentful (under _Settings_ -> _API Keys_): 
- `Space ID` 
- `Content Delivery API - access token`.

I hope this helps 🙂
